# Generated by Django 5.0.4 on 2025-06-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_expedicion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='certificados/images')),
            ],
            options={
                'verbose_name': 'Certificación',
                'verbose_name_plural': 'Certificaciones',
                'ordering': ['fecha_expedicion'],
            },
        ),
    ]
